asn1c: use BSD-2-Clause instead of ambiguous BSD
* fixes:
  ERROR: asn1c-native-0.9.28-r0 do_populate_lic: QA Issue: asn1c-native: No generic license file exists for: BSD in any provider [license-exists]

  after ambiguous BSD license text was removed in:
  https://git.openembedded.org/openembedded-core/commit/?h=kirkstone&id=14d4c007c49652d836d325a12bdbcd3bfa42e6d5

Signed-off-by: Martin Jansa <martin2.jansa@lgepartner.com>